export enum ErrorCode {
  Forbidden_Resource = 'Forbidden_Resource',
  Unauthorized = 'Unauthorized',
  UnprocessableEntity = 'UnprocessableEntity',
  InternalServerError = 'InternalServerError',
  BadRequest = 'BadRequest',
  NotFound = 'NotFound',
  UserNotExist = 'UserNotExist',
  PasswordNotMatch = 'PasswordNotMatch',
  Invalid_Input = 'Invalid_Input',
  UserExist = 'UserExist',
  VerifyCodeNotMatch = 'VerifyCodeNotMatch',
  VerifyCodeExpired = 'VerifyCodeExpired',
  LocationNotFound = 'LocationNotFound',
}
